[package]
name = "mbqueue"
version = "0.1.0"
edition = "2021"

[lib]
name = "mbqueue"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.27"
